/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Course;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Coursename
 */
public class CoursenameTest {
    private final Coursename model = new Coursename();

    /**
     * Model tests for Coursename
     */
    @Test
    public void testCoursename() {
        // TODO: test Coursename
    }

    /**
     * Test the property 'getcoursenameid'
     */
    @Test
    public void getcoursenameidTest() {
        // TODO: test getcoursenameid
    }

    /**
     * Test the property 'getcoursename'
     */
    @Test
    public void getcoursenameTest() {
        // TODO: test getcoursename
    }

    /**
     * Test the property 'coursenames'
     */
    @Test
    public void coursenamesTest() {
        // TODO: test coursenames
    }

}
