/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Coursename;
import org.openapitools.client.model.Degreetype;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Course
 */
public class CourseTest {
    private final Course model = new Course();

    /**
     * Model tests for Course
     */
    @Test
    public void testCourse() {
        // TODO: test Course
    }

    /**
     * Test the property 'getcourseid'
     */
    @Test
    public void getcourseidTest() {
        // TODO: test getcourseid
    }

    /**
     * Test the property 'getdegreetype'
     */
    @Test
    public void getdegreetypeTest() {
        // TODO: test getdegreetype
    }

    /**
     * Test the property 'getcoursename'
     */
    @Test
    public void getcoursenameTest() {
        // TODO: test getcoursename
    }

    /**
     * Test the property 'students'
     */
    @Test
    public void studentsTest() {
        // TODO: test students
    }

}
