/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Course;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Coursename
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-15T13:09:53.193681Z[Europe/London]")
public class Coursename {
  public static final String SERIALIZED_NAME_GETCOURSENAMEID = "getcoursenameid";
  @SerializedName(SERIALIZED_NAME_GETCOURSENAMEID)
  private Integer getcoursenameid;

  public static final String SERIALIZED_NAME_GETCOURSENAME = "getcoursename";
  @SerializedName(SERIALIZED_NAME_GETCOURSENAME)
  private String getcoursename;

  public static final String SERIALIZED_NAME_COURSENAMES = "coursenames";
  @SerializedName(SERIALIZED_NAME_COURSENAMES)
  private List<Course> coursenames = null;

  public Coursename() {
  }

  public Coursename getcoursenameid(Integer getcoursenameid) {
    
    this.getcoursenameid = getcoursenameid;
    return this;
  }

   /**
   * Get getcoursenameid
   * @return getcoursenameid
  **/
  @javax.annotation.Nullable

  public Integer getGetcoursenameid() {
    return getcoursenameid;
  }


  public void setGetcoursenameid(Integer getcoursenameid) {
    this.getcoursenameid = getcoursenameid;
  }


  public Coursename getcoursename(String getcoursename) {
    
    this.getcoursename = getcoursename;
    return this;
  }

   /**
   * Get getcoursename
   * @return getcoursename
  **/
  @javax.annotation.Nullable

  public String getGetcoursename() {
    return getcoursename;
  }


  public void setGetcoursename(String getcoursename) {
    this.getcoursename = getcoursename;
  }


  public Coursename coursenames(List<Course> coursenames) {
    
    this.coursenames = coursenames;
    return this;
  }

  public Coursename addCoursenamesItem(Course coursenamesItem) {
    if (this.coursenames == null) {
      this.coursenames = new ArrayList<>();
    }
    this.coursenames.add(coursenamesItem);
    return this;
  }

   /**
   * Get coursenames
   * @return coursenames
  **/
  @javax.annotation.Nullable

  public List<Course> getCoursenames() {
    return coursenames;
  }


  public void setCoursenames(List<Course> coursenames) {
    this.coursenames = coursenames;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Coursename coursename = (Coursename) o;
    return Objects.equals(this.getcoursenameid, coursename.getcoursenameid) &&
        Objects.equals(this.getcoursename, coursename.getcoursename) &&
        Objects.equals(this.coursenames, coursename.coursenames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getcoursenameid, getcoursename, coursenames);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Coursename {\n");
    sb.append("    getcoursenameid: ").append(toIndentedString(getcoursenameid)).append("\n");
    sb.append("    getcoursename: ").append(toIndentedString(getcoursename)).append("\n");
    sb.append("    coursenames: ").append(toIndentedString(coursenames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("getcoursenameid");
    openapiFields.add("getcoursename");
    openapiFields.add("coursenames");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Coursename
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Coursename.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Coursename is not found in the empty JSON string", Coursename.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Coursename.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Coursename` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("getcoursename") != null && !jsonObj.get("getcoursename").isJsonNull()) && !jsonObj.get("getcoursename").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `getcoursename` to be a primitive type in the JSON string but got `%s`", jsonObj.get("getcoursename").toString()));
      }
      if (jsonObj.get("coursenames") != null && !jsonObj.get("coursenames").isJsonNull()) {
        JsonArray jsonArraycoursenames = jsonObj.getAsJsonArray("coursenames");
        if (jsonArraycoursenames != null) {
          // ensure the json data is an array
          if (!jsonObj.get("coursenames").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `coursenames` to be an array in the JSON string but got `%s`", jsonObj.get("coursenames").toString()));
          }

          // validate the optional field `coursenames` (array)
          for (int i = 0; i < jsonArraycoursenames.size(); i++) {
            Course.validateJsonObject(jsonArraycoursenames.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Coursename.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Coursename' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Coursename> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Coursename.class));

       return (TypeAdapter<T>) new TypeAdapter<Coursename>() {
           @Override
           public void write(JsonWriter out, Coursename value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Coursename read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Coursename given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Coursename
  * @throws IOException if the JSON string is invalid with respect to Coursename
  */
  public static Coursename fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Coursename.class);
  }

 /**
  * Convert an instance of Coursename to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

