/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Course;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Degreetype
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-15T13:09:53.193681Z[Europe/London]")
public class Degreetype {
  public static final String SERIALIZED_NAME_GETDEGREETYPEID = "getdegreetypeid";
  @SerializedName(SERIALIZED_NAME_GETDEGREETYPEID)
  private Integer getdegreetypeid;

  public static final String SERIALIZED_NAME_TYPENAME = "typename";
  @SerializedName(SERIALIZED_NAME_TYPENAME)
  private String typename;

  public static final String SERIALIZED_NAME_SHORTCODE = "shortcode";
  @SerializedName(SERIALIZED_NAME_SHORTCODE)
  private String shortcode;

  public static final String SERIALIZED_NAME_DEGREETYPE = "degreetype";
  @SerializedName(SERIALIZED_NAME_DEGREETYPE)
  private List<Course> degreetype = null;

  public Degreetype() {
  }

  public Degreetype getdegreetypeid(Integer getdegreetypeid) {
    
    this.getdegreetypeid = getdegreetypeid;
    return this;
  }

   /**
   * Get getdegreetypeid
   * @return getdegreetypeid
  **/
  @javax.annotation.Nullable

  public Integer getGetdegreetypeid() {
    return getdegreetypeid;
  }


  public void setGetdegreetypeid(Integer getdegreetypeid) {
    this.getdegreetypeid = getdegreetypeid;
  }


  public Degreetype typename(String typename) {
    
    this.typename = typename;
    return this;
  }

   /**
   * Get typename
   * @return typename
  **/
  @javax.annotation.Nullable

  public String getTypename() {
    return typename;
  }


  public void setTypename(String typename) {
    this.typename = typename;
  }


  public Degreetype shortcode(String shortcode) {
    
    this.shortcode = shortcode;
    return this;
  }

   /**
   * Get shortcode
   * @return shortcode
  **/
  @javax.annotation.Nullable

  public String getShortcode() {
    return shortcode;
  }


  public void setShortcode(String shortcode) {
    this.shortcode = shortcode;
  }


  public Degreetype degreetype(List<Course> degreetype) {
    
    this.degreetype = degreetype;
    return this;
  }

  public Degreetype addDegreetypeItem(Course degreetypeItem) {
    if (this.degreetype == null) {
      this.degreetype = new ArrayList<>();
    }
    this.degreetype.add(degreetypeItem);
    return this;
  }

   /**
   * Get degreetype
   * @return degreetype
  **/
  @javax.annotation.Nullable

  public List<Course> getDegreetype() {
    return degreetype;
  }


  public void setDegreetype(List<Course> degreetype) {
    this.degreetype = degreetype;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Degreetype degreetype = (Degreetype) o;
    return Objects.equals(this.getdegreetypeid, degreetype.getdegreetypeid) &&
        Objects.equals(this.typename, degreetype.typename) &&
        Objects.equals(this.shortcode, degreetype.shortcode) &&
        Objects.equals(this.degreetype, degreetype.degreetype);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getdegreetypeid, typename, shortcode, degreetype);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Degreetype {\n");
    sb.append("    getdegreetypeid: ").append(toIndentedString(getdegreetypeid)).append("\n");
    sb.append("    typename: ").append(toIndentedString(typename)).append("\n");
    sb.append("    shortcode: ").append(toIndentedString(shortcode)).append("\n");
    sb.append("    degreetype: ").append(toIndentedString(degreetype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("getdegreetypeid");
    openapiFields.add("typename");
    openapiFields.add("shortcode");
    openapiFields.add("degreetype");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Degreetype
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Degreetype.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Degreetype is not found in the empty JSON string", Degreetype.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Degreetype.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Degreetype` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("typename") != null && !jsonObj.get("typename").isJsonNull()) && !jsonObj.get("typename").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `typename` to be a primitive type in the JSON string but got `%s`", jsonObj.get("typename").toString()));
      }
      if ((jsonObj.get("shortcode") != null && !jsonObj.get("shortcode").isJsonNull()) && !jsonObj.get("shortcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shortcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shortcode").toString()));
      }
      if (jsonObj.get("degreetype") != null && !jsonObj.get("degreetype").isJsonNull()) {
        JsonArray jsonArraydegreetype = jsonObj.getAsJsonArray("degreetype");
        if (jsonArraydegreetype != null) {
          // ensure the json data is an array
          if (!jsonObj.get("degreetype").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `degreetype` to be an array in the JSON string but got `%s`", jsonObj.get("degreetype").toString()));
          }

          // validate the optional field `degreetype` (array)
          for (int i = 0; i < jsonArraydegreetype.size(); i++) {
            Course.validateJsonObject(jsonArraydegreetype.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Degreetype.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Degreetype' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Degreetype> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Degreetype.class));

       return (TypeAdapter<T>) new TypeAdapter<Degreetype>() {
           @Override
           public void write(JsonWriter out, Degreetype value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Degreetype read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Degreetype given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Degreetype
  * @throws IOException if the JSON string is invalid with respect to Degreetype
  */
  public static Degreetype fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Degreetype.class);
  }

 /**
  * Convert an instance of Degreetype to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

